# Generated by Django 5.2.12 on 2026-03-09 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_remove_matakuliah_deskrpsi_matakuliah_deskripsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('angkatan', models.PositiveIntegerField(help_text='Contoh: 2024')),
            ],
            options={
                'verbose_name_plural': 'Mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(help_text='Contoh: A, B, atau DS-01', max_length=10)),
                ('tahun_akademik', models.CharField(help_text='Contoh: Ganjil 2025/2026', max_length=20)),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_dibuka', to='curriculum.matakuliah')),
            ],
            options={
                'verbose_name_plural': 'Kelas Perkuliahan',
            },
        ),
        migrations.CreateModel(
            name='PesertaKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta', to='assessments.kelas')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_diikuti', to='assessments.mahasiswa')),
            ],
            options={
                'verbose_name_plural': 'Peserta Kelas',
                'unique_together': {('kelas', 'mahasiswa')},
            },
        ),
        migrations.CreateModel(
            name='NilaiSubCPMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_angka', models.DecimalField(decimal_places=2, default=0.0, help_text='Nilai skala 0-100', max_digits=5)),
                ('sub_cpmk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subcpmk')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_subcpmk', to='assessments.pesertakelas')),
            ],
            options={
                'verbose_name_plural': 'Nilai Sub-CPMK',
                'unique_together': {('peserta', 'sub_cpmk')},
            },
        ),
    ]
