# Generated by Django 5.2.12 on 2026-03-16 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('nim', models.CharField(blank=True, max_length=20)),
                ('angkatan', models.PositiveIntegerField()),
                ('tahun_lulus', models.PositiveIntegerField()),
                ('pekerjaan', models.CharField(blank=True, max_length=200)),
                ('instansi', models.CharField(blank=True, max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alumni/')),
                ('testimoni', models.TextField(blank=True)),
                ('ditampilkan', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumni',
                'ordering': ['-tahun_lulus'],
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('kategori', models.CharField(choices=[('berita', 'Berita'), ('pengumuman', 'Pengumuman'), ('kegiatan', 'Kegiatan'), ('prestasi', 'Prestasi')], default='berita', max_length=20)),
                ('isi', models.TextField()),
                ('ringkasan', models.TextField(blank=True, max_length=300)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('diterbitkan', models.BooleanField(default=False)),
                ('tanggal_dibuat', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Berita',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('nip', models.CharField(blank=True, max_length=30)),
                ('nidn', models.CharField(blank=True, max_length=20)),
                ('jabatan', models.CharField(choices=[('koordinator', 'Koordinator Prodi'), ('dosen', 'Dosen'), ('dosen_luar', 'Dosen Luar Biasa')], default='dosen', max_length=20)),
                ('pendidikan_terakhir', models.CharField(choices=[('s3', 'S3 / Doktor'), ('s2', 'S2 / Magister')], default='s2', max_length=5)),
                ('bidang_keahlian', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='dosen/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('google_scholar', models.URLField(blank=True)),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampil di halaman')),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dosen',
                'verbose_name_plural': 'Dosen',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('jenis', models.CharField(choices=[('laboratorium', 'Laboratorium'), ('ruang_kuliah', 'Ruang Kuliah'), ('ruang_dosen', 'Ruang Dosen'), ('lainnya', 'Lainnya')], default='laboratorium', max_length=20)),
                ('deskripsi', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fasilitas/')),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fasilitas',
                'verbose_name_plural': 'Fasilitas',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True)),
                ('foto', models.ImageField(upload_to='galeri/')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('ditampilkan', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Galeri',
                'verbose_name_plural': 'Galeri',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjek', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('sudah_dibaca', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pesan Kontak',
                'verbose_name_plural': 'Pesan Kontak',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='ProfilProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sejarah', models.TextField()),
                ('visi', models.TextField()),
                ('misi', models.TextField(help_text='Pisahkan tiap misi dengan baris baru')),
                ('tujuan', models.TextField(blank=True)),
                ('akreditasi', models.CharField(default='Baik', max_length=50)),
                ('tahun_berdiri', models.PositiveIntegerField(default=2020)),
                ('jumlah_mahasiswa', models.PositiveIntegerField(default=0)),
                ('jumlah_dosen', models.PositiveIntegerField(default=0)),
                ('email_prodi', models.EmailField(blank=True, max_length=254)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Profil Prodi',
                'verbose_name_plural': 'Profil Prodi',
            },
        ),
        migrations.CreateModel(
            name='TenagaKependidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('nip', models.CharField(blank=True, max_length=30)),
                ('jabatan', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='tendik/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenaga Kependidikan',
                'verbose_name_plural': 'Tenaga Kependidikan',
                'ordering': ['nama'],
            },
        ),
    ]
