# Generated by Django 5.2.12 on 2026-03-09 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(help_text='Contoh: Pengantar Sains Data', max_length=150)),
                ('sks', models.PositiveIntegerField(default=3)),
                ('semester', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Mata Kuliah',
            },
        ),
        migrations.CreateModel(
            name='ProfilLulusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: PL01', max_length=10, unique=True)),
                ('nama', models.CharField(help_text='Contoh: Data Scientist, AI Engineer', max_length=100)),
                ('deskripsi', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Profil Lulusan',
            },
        ),
        migrations.CreateModel(
            name='CPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: PLO1 atau CPL01', max_length=10, unique=True)),
                ('deskripsi', models.TextField()),
                ('profil_lulusan', models.ManyToManyField(help_text='Pilih profil lulusan yang ditunjang oleh CPL ini', related_name='cpl_terkait', to='curriculum.profillulusan')),
            ],
            options={
                'verbose_name_plural': 'Capaian Pembelajaran Lulusan (CPL)',
            },
        ),
        migrations.CreateModel(
            name='RPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_penyusunan', models.DateField()),
                ('deskripsi', models.TextField()),
                ('mata_kuliah', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rps', to='curriculum.matakuliah')),
            ],
            options={
                'verbose_name_plural': 'Rencana Pembelajaran Semester (RPS)',
            },
        ),
        migrations.CreateModel(
            name='CPMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: CPMK 1', max_length=10)),
                ('deskripsi', models.TextField()),
                ('cpl', models.ManyToManyField(related_name='cpmk_terkait', to='curriculum.cpl')),
                ('rps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpmk', to='curriculum.rps')),
            ],
            options={
                'verbose_name_plural': 'Capaian Pembelajaran Mata Kuliah (CPMK)',
            },
        ),
        migrations.CreateModel(
            name='SubCPMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: Sub-CPMK 1', max_length=15)),
                ('deskripsi', models.TextField()),
                ('bobot_persentase', models.DecimalField(decimal_places=2, help_text='Bobot Sub-CPMK terhadap mata kuliah dalam persen (%)', max_digits=5)),
                ('cpmk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cpmk', to='curriculum.cpmk')),
            ],
            options={
                'verbose_name_plural': 'Sub-CPMK',
            },
        ),
    ]
