# Generated by Django 5.2.12 on 2026-03-09 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpmk',
            name='rps',
        ),
        migrations.AddField(
            model_name='cpmk',
            name='mata_kuliah',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cpmk', to='curriculum.matakuliah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcpmk',
            name='bentuk_penilaian',
            field=models.CharField(blank=True, help_text='Contoh: Tugas, Case Method (CM), Quiz, MID, FINAL', max_length=50, null=True),
        ),
    ]
