# Generated by Django 5.2.12 on 2026-03-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_cpmk_rps_cpmk_mata_kuliah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='deskrpsi',
            field=models.CharField(default='deskripsi mata kuliah', max_length=1000),
            preserve_default=False,
        ),
    ]
