# Generated by Django 5.2.12 on 2026-03-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_matakuliah_deskrpsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matakuliah',
            name='deskrpsi',
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='deskripsi',
            field=models.TextField(default='Deskripsi Mata Kuliah'),
            preserve_default=False,
        ),
    ]
